export interface IDXIndex {
  slug: string;
  name: string;
  fullName: string;
  description: string;
  stocks: string[];
}

export const IDX_INDICES: IDXIndex[] = [
  {
    slug: "smc-liquid",
    name: "SMC Liquid",
    fullName: "IDX SMC Liquid",
    description:
      "Indeks SMC Liquid (Small-Mid-Cap Liquid) BEI mencakup saham-saham dengan kapitalisasi menengah-kecil yang memiliki likuiditas tinggi. Saham-saham dalam indeks ini dipilih berdasarkan volume perdagangan dan frekuensi transaksi, menjadikannya acuan untuk investor yang mencari saham likuid di luar LQ45/IDX40.",
    stocks: [
      "ACES.JK",
      "ADHI.JK",
      "AKRA.JK",
      "ANTM.JK",
      "BRIS.JK",
      "CPIN.JK",
      "EXCL.JK",
      "INCO.JK",
      "INKP.JK",
      "ITMG.JK",
      "JPFA.JK",
      "JSMR.JK",
      "KLBF.JK",
      "MAPI.JK",
      "MDKA.JK",
      "MEDC.JK",
      "PGAS.JK",
      "SMGR.JK",
      "TINS.JK",
      "TOWR.JK",
      "UNTR.JK",
      "UNVR.JK",
    ],
  },
  {
    slug: "idx30",
    name: "IDX30",
    fullName: "Indeks IDX30",
    description:
      "Indeks IDX30 BEI mengukur performa harga dari 30 saham yang memiliki likuiditas tinggi dan fundamental baik serta listing history yang panjang di Bursa Efek Indonesia.",
    stocks: [
      "BBCA.JK",
      "BBRI.JK",
      "BMRI.JK",
      "TLKM.JK",
      "ASII.JK",
      "BBNI.JK",
      "BRIS.JK",
      "ICBP.JK",
      "AMRT.JK",
      "GOTO.JK",
      "UNTR.JK",
      "BRPT.JK",
      "CPIN.JK",
      "INDF.JK",
      "ADRO.JK",
      "KLBF.JK",
      "ISAT.JK",
      "AMMN.JK",
      "MDKA.JK",
      "MBMA.JK",
      "PGAS.JK",
      "TOWR.JK",
      "ARTO.JK",
      "ADMR.JK",
      "MAPI.JK",
      "AKRA.JK",
      "SMGR.JK",
      "MAPA.JK",
      "JPFA.JK",
      "ANTM.JK",
    ],
  },
  {
    slug: "idx-quality",
    name: "IDX Quality",
    fullName: "Indeks IDX Quality30",
    description:
      "Indeks IDX Quality30 BEI terdiri dari 30 saham dengan kualitas fundamental terbaik berdasarkan kriteria Return on Equity (ROE), pertumbuhan laba, dan leverage yang sehat.",
    stocks: [
      "BBCA.JK",
      "BBRI.JK",
      "BMRI.JK",
      "TLKM.JK",
      "ASII.JK",
      "BBNI.JK",
      "BRIS.JK",
      "ICBP.JK",
      "UNTR.JK",
      "CPIN.JK",
      "INDF.JK",
      "ADRO.JK",
      "KLBF.JK",
      "AMMN.JK",
      "MDKA.JK",
      "MBMA.JK",
      "ARTO.JK",
      "ADMR.JK",
      "MAPI.JK",
      "AKRA.JK",
      "SMGR.JK",
      "ITMG.JK",
      "MEDC.JK",
      "TOWR.JK",
      "PGAS.JK",
      "JSMR.JK",
      "SIDO.JK",
      "INKP.JK",
      "BRPT.JK",
      "AMRT.JK",
    ],
  },
];
