import * as fs from "fs";
import * as path from "path";

const SECTOR_MAP: Record<string, string> = {
  basic_materials: "Basic Materials",
  consumer_cylicals: "Consumer Cyclicals",
  consumer_non_cylicals: "Consumer Non-Cyclicals",
  energy: "Energy",
  financials: "Financials",
  healthcare: "Healthcare",
  industrials: "Industrials",
  infrastructures: "Infrastructures",
  properties_real_estate: "Properties & Real Estate",
  technology: "Technology",
  transporation_logistics: "Transportation & Logistics",
};

const IDX40_TICKERS_RAW = [
  "BBCA", "BBRI", "AMMN", "BMRI", "TLKM", "ASII", "BBNI", "BRIS", "ICBP", "AMRT",
  "GOTO", "UNTR", "BRPT", "CPIN", "INDF", "ADRO", "KLBF", "ISAT", "UNVR", "ANTM",
  "PGAS", "MDKA", "PGEO", "MBMA", "ADMR", "INKP", "INCO", "PTBA", "EXCL", "TOWR",
  "ITMG", "JSMR", "ARTO", "MEDC", "MAPI", "AKRA", "MAPA", "JPFA", "SMGR", "SIDO",
];
const IDX40_TICKERS = new Set(IDX40_TICKERS_RAW.map((t) => t + ".JK"));

const INPUT_DIR = path.resolve(process.argv[2] || path.join(process.env.HOME!, "Downloads/idx_stock_list"));
const OUTPUT_FILE = path.resolve(process.argv[3] || path.join(__dirname, "../src/lib/idx-stocks.ts"));

interface RawStock {
  Code: string;
  Name: string;
  ListingDate: string;
  Shares: number;
  ListingBoard: string;
}

interface ParsedStock {
  ticker: string;
  name: string;
  sector: string;
  listingBoard: string;
}

function main() {
  const stocks: ParsedStock[] = [];

  for (const [sectorId, sectorName] of Object.entries(SECTOR_MAP)) {
    const filePath = path.join(INPUT_DIR, `${sectorId}.json`);
    if (!fs.existsSync(filePath)) {
      console.warn(`Missing: ${filePath}`);
      continue;
    }

    const raw = JSON.parse(fs.readFileSync(filePath, "utf-8"));
    const data: RawStock[] = raw.data ?? [];

    for (const s of data) {
      stocks.push({
        ticker: s.Code + ".JK",
        name: s.Name.replace(/\s*Tbk\.?\s*$/i, "").trim(),
        sector: sectorName,
        listingBoard: s.ListingBoard,
      });
    }
  }

  // Sort by ticker
  stocks.sort((a, b) => a.ticker.localeCompare(b.ticker));

  const tickers = stocks.map((s) => s.ticker);
  const idx40Tickers = tickers.filter((t) => IDX40_TICKERS.has(t));

  // Generate TypeScript
  const sectorsEntries = Object.entries(SECTOR_MAP)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(",\n");

  const stocksEntries = stocks
    .map((s) => `  { ticker: ${JSON.stringify(s.ticker)}, name: ${JSON.stringify(s.name)}, sector: ${JSON.stringify(s.sector)}, listingBoard: ${JSON.stringify(s.listingBoard)} }`)
    .join(",\n");

  const idx40Entries = idx40Tickers.map((t) => `  ${JSON.stringify(t)}`).join(",\n");

  const code = `// Auto-generated by scripts/generate-stocks.ts — do not edit manually
// Generated: ${new Date().toISOString()}
// Total stocks: ${stocks.length}, IDX40: ${idx40Tickers.length}

export const IDX_SECTORS: Record<string, string> = {
${sectorsEntries}
};

export interface IDXStockFull {
  ticker: string;
  name: string;
  sector: string;
  listingBoard: string;
}

export const IDX_STOCKS: IDXStockFull[] = [
${stocksEntries}
];

export const IDX40_TICKERS: string[] = [
${idx40Entries}
];

export const ALL_TICKERS: string[] = IDX_STOCKS.map((s) => s.ticker);

export function isIDX40(ticker: string): boolean {
  return IDX40_TICKERS.includes(ticker);
}
`;

  fs.writeFileSync(OUTPUT_FILE, code);
  console.log(`Generated ${stocks.length} stocks (${idx40Tickers.length} IDX40) → ${OUTPUT_FILE}`);
}

main();
